
const User = {
    display_name: String,
    username: String,
    id: String,
    email: String,
    bio: String,
    socials: {
        facebook: String,
        twitter: String,
        linkedin: String,
        github: String,
        telegram: String,
    },
    wallet_address: String,
    kyc_status: Boolean,
    is_verified: Boolean,
    is_admin: Boolean,
    pfp: String,
    total_earned: Number,
    participated_bounties: [Project],
    completed_bounties: [Project],
    ongoing_bounties: [Project],
    skills: [String],
    job_preferences: [String],
    personal_work_sample: [Project],
    teammates: [String],
    upcoming_payments: [Payment],
    past_payments: [Payment],
    notifications: [Notification],
    reward_history: [Reward],
}

const Project = {
    title: String,
    description: String,
    image: String,
    category: [String],
    sponsor: String,
    interested_users: Number,
    proposals_count: Number,
    about: String,
    milestone: [Milestone],
    status: String,
    deadline: Date,
    created_at: Date,
    updated_at: Date,
    delivery_time: Date,
    comments: [Comment],
    user_id: String,
}

const Milestone = {
    title: String,
    description: String,
    deadline: Date,
    status: String,
    created_at: Date,
    updated_at: Date,
    prize: Number,
    currenct: String,
    delivery_time: Date,
    comments: [Comment],
    status: ['pending', 'completed', 'rejected', 'idle', 'under_review', 'in_progress'],
    starts_in: Data,
    help_link: [String],
    claim_payment: String(url to payment site),
    team_details: [User],
    user_status: ['pending', 'completed', 'rejected', 'idle', 'under_review', 'in_progress', 'missed_deadline'],
    payment_address: User.wallet_address,
    type: "Bounty"
}